name = "LLVM"
uuid = "929cbde3-209d-540e-8aea-75f648917ca0"
version = "6.0.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
LLVMExtra_jll = "dad2f222-ce93-54a1-a47d-0025e8a3acab"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
CEnum = "0.2, 0.3, 0.4"
LLVMExtra_jll = "=0.0.22"
julia = "1.6"
