[general]
library_name = "libLLVMExtra"
prologue_file_path = ""
epilogue_file_path = ""
use_julia_native_enum_type = false
use_deterministic_symbol = true
generate_isystem_symbols = false
printer_blacklist = [
    "LLVM_C_STRICT_PROTOTYPES_END",
    "LLVM_NATIVE_ARCH",
    "LLVM_C_EXTERN_C_BEGIN",
    "LLVM_C_EXTERN_C_END",
    "HUGE_VALF",
]

[codegen]
use_julia_bool = true
always_NUL_terminated_string = true
is_function_strictly_typed = false
opaque_func_arg_as_PtrCvoid = false
opaque_as_mutable_struct = true

[codegen.macro]
macro_mode = "basic"
add_comment_for_skipped_macro = false

