[deps]
CMake_jll = "3f4e10e2-61f2-5801-8945-23b9d642d0e6"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
LLVMExtra_jll = "dad2f222-ce93-54a1-a47d-0025e8a3acab"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
