name: CI
on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:
jobs:
  binary_test:
    name: Julia ${{ matrix.version }} ${{ matrix.llvm_args }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.8', '1.9', 'nightly']
        os: ['ubuntu-latest', 'macOS-latest', 'windows-latest']
        arch: [x64]
        llvm_args: ['']
        include:
          # on Julia 1.10, we can enable opaque pointers
          - version: 'nightly'
            os: 'ubuntu-latest'
            arch: 'x64'
            llvm_args: '--opaque-pointers'
          - version: 'nightly'
            os: 'macOS-latest'
            arch: 'x64'
            llvm_args: '--opaque-pointers'
          - version: 'nightly'
            os: 'windows-latest'
            arch: 'x64'
            llvm_args: '--opaque-pointers'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # build_ci.jl needs to be able to inspect the git log

      # install Julia
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # set-up packages
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          install: mingw-w64-x86_64-gcc
        if: runner.os == 'Windows'

      - name: Build libLLVMExtra
        run: julia --project=deps deps/build_ci.jl
        if: runner.os != 'Windows'
      - name: Build libLLVMExtra (in msys2)
        shell: msys2 {0}
        run: julia --project=deps deps/build_ci.jl
        if: runner.os == 'Windows'

      - name: Run tests
        run: julia --project -e 'using Pkg; Pkg.test(; coverage=true, julia_args=`-g2`)'
        env:
          JULIA_LLVM_ARGS: ${{ matrix.llvm_args }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info

  # development versions, built from source (with assertions enabled)
  source_test:
    name: Julia ${{ matrix.branch }} ${{ matrix.llvm_args }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        branch: ['release-1.8', 'release-1.9', 'master']
        os: ['ubuntu-latest', 'macOS-latest', 'windows-latest']
        arch: ['x64']
        llvm_args: ['']
        include:
          # on Julia 1.10, we can enable opaque pointers
          - branch: 'master'
            os: 'ubuntu-latest'
            arch: 'x64'
            llvm_args: '--opaque-pointers'
          # JuliaLang/julia#48081
          #- branch: 'master'
          #  os: 'windows-latest'
          #  arch: 'x64'
          #  llvm_args: '--opaque-pointers'
          # hangs
          #- branch: 'master'
          #  os: 'macOS-latest'
          #  arch: 'x64'
          #  llvm_args: '--opaque-pointers'
        exclude:
          # JuliaLang/julia#48081
          - branch: 'master'
            os: 'windows-latest'
            arch: 'x64'
          # hangs
          - branch: 'master'
            os: 'macOS-latest'
            arch: 'x64'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # build_ci.jl needs to be able to inspect the git log
      - uses: actions/checkout@v3
        with:
          repository: 'JuliaLang/julia'
          ref: ${{ matrix.branch }}
          path: 'julia'

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          install: mingw-w64-x86_64-gcc cmake diffutils git m4 make patch tar p7zip curl python
        if: runner.os == 'Windows'

      # compile Julia
      - name: Compile Julia
        run: |
          mv julia ../  # move julia checkout out of the way, for ReTestItems.jl
          sed -i.bak 's/exit 2/exit 0/g' ../julia/deps/tools/jlchecksum
          make -C ../julia -j $(nproc) FORCE_ASSERTIONS=1 LLVM_ASSERTIONS=1 JULIA_PRECOMPILE=0
          echo $PWD/../julia/usr/bin >> $GITHUB_PATH
        if: runner.os != 'Windows'
      - name: Compile Julia (in msys2)
        shell: msys2 {0}
        run: |
          mv julia ../  # move julia checkout out of the way, for ReTestItems.jl
          sed -i.bak 's/exit 2/exit 0/g' ../julia/deps/tools/jlchecksum
          # XXX: workaround for JuliaLang/julia#48081
          make -C ../julia/deps install-csl && \
          cp ${MINGW_PREFIX}/lib/libmsvcrt.a ../julia/usr/lib/libmsvcrt.a && \
          make -C ../julia -j $(nproc) FORCE_ASSERTIONS=1 LLVM_ASSERTIONS=1 JULIA_PRECOMPILE=0
          echo $PWD/../julia/usr/bin >> $GITHUB_PATH
        if: runner.os == 'Windows'

      # set-up packages
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1

      - name: Build libLLVMExtra
        run: julia --project=deps deps/build_ci.jl
        if: runner.os != 'Windows'
      - name: Build libLLVMExtra (in msys2)
        shell: msys2 {0}
        run: julia --project=deps deps/build_ci.jl
        if: runner.os == 'Windows'

      - name: Run tests
        run: julia --project -e 'using Pkg; Pkg.test(; coverage=true, julia_args=`-g2`)'
        env:
          JULIA_LLVM_ARGS: ${{ matrix.llvm_args }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.8'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs/ docs/make.jl
